In [4]:
import os

In [5]:
%pwd

'c:\\Users\\LENOVO\\Animal_Classifier\\notebooks'

In [6]:
os.chdir("../")

In [7]:
%pwd

'c:\\Users\\LENOVO\\Animal_Classifier'

In [10]:
import numpy as np

# Load saved data
X_train = np.load("X_train.npy")
y_train = np.load("y_train.npy")

# Print shapes
print("Training Data Shape:", X_train.shape)  # Expected: (N, 224, 224, 3)
print("Training Labels Shape:", y_train.shape)  # Expected: (N, 15)

# Check one-hot encoding (first 5 labels)
print("First 5 Labels:\n", y_train[:5])


Training Data Shape: (1360, 224, 224, 3)
Training Labels Shape: (1360, 15)
First 5 Labels:
 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [11]:
import numpy as np

DATA_PATH = "preprocessed_data/"

# Load and check dataset
X_train = np.load(DATA_PATH + "X_train.npy")
y_train = np.load(DATA_PATH + "y_train.npy")

print("X_train dtype:", X_train.dtype)
print("y_train dtype:", y_train.dtype)

print("X_train shape:", X_train.shape)  # Expected: (XXXX, 224, 224, 3)
print("y_train shape:", y_train.shape)  # Expected: (XXXX, 15)


X_train dtype: float32
y_train dtype: float64
X_train shape: (1360, 224, 224, 3)
y_train shape: (1360, 15)
